### ISSUE TITLE
B1 links and cyclical links

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devdocs#6]
There are links that lead back to the b1 docs: http://docs.eosnetwork.com/next/eosdocs/client-side/jsdocs/

I see these are coming from https://github.com/eosnetworkfoundation/mandel-eosjs 

Looks like we need to go through the readmes and make sure there's no links to b1 docs either
Also, the fact that the links are cyclical is strange (readme leading to docs which lead to readme)

**Comment by ericpassmore** [comment]
- [ ] mandel-eosjs/README.md
  * Javascript API for integration with EOSIO-based blockchains using [EOSIO RPC API](https://developers.eos.io/eosio-nodeos/reference).

- [ ] mandel-eosjs/CONTRIBUTING.md
   * Integration tests will only work with a local node running on port 8888 and with test accounts "bob" and "alice".  This 
can be accomplished by following the [EOSIO Developer Getting Started Guide](https://developers.eos.io/eosio-home/docs/getting-the-software#section-step-1-1-start-keosd).

- [ ] mandel-swift/EXAMPLES.md
  * This snippet retrieves information for an account on the blockchain. There are several layers of response to unpack if all information is desired. Some portions of the response are not fully unmarshalled, either due to size or because the responses can vary in structure. These are returned as general `[String: Any]` Swift objects. The [NODEOS Reference]. 
   *(https://developers.eos.io/manuals/eos/latest/nodeos/plugins/chain_api_plugin/api-reference/index) is helpful for decoding the parts of responses that are not fully unmarshalled.
current milestone](https://github.com/EOSIO/eosjs/issues?q=is%3Aissue+is%3Aclosed) or try to reproduce it
[Report a bug](https://github.com/EOSIO/eosjs/issues/new?template=bug_report.md)
Code contributions are welcome and encouraged! If you are looking for a good place to start, check out the [good first issue](https://github.com/EOSIO/eosjs/labels/good%20first%20issue) label in GitHub issues.
  * [develop](https://github.com/EOSIO/eosjs/tree/develop)** is the development branch. All work on the next release happens here so you should generally branch off `develop`. Do **NOT** use this branch for a production site.
   * [master](https://github.com/EOSIO/eosjs/tree/master)** contains the latest release of EOSJS. This branch may be used in production. Do **NOT** use this branch to work on EOSJS's source.

- [ ] mandel-swift/README.md
  * EosioSwift, the core component for communicating and transacting with EOSIO-based blockchains using the [EOSIO RPC API](https://developers.eos.io/manuals/eos/latest/nodeos/plugins/chain_api_plugin/api-reference/index).
The RPC Provider is responsible for all [RPC calls to nodeos](https://developers.eos.io/manuals/eos/latest/nodeos/plugins/chain_api_plugin/api-reference/index), as well as general network handling (Reachability, retry logic, etc.) While EOSIO SDK for Swift includes an [RPC Provider implementation](#rpc-using-the-default-rpc-provider), it must still be set explicitly when creating an `EosioTransaction`, as it must be instantiated with an endpoint. (The default implementation suffices for most use cases.)
  * [Nodeos RPC Reference Documentation](https://developers.eos.io/manuals/eos/latest/nodeos/plugins/chain_api_plugin/api-reference/index) - Nodeos RPC reference.
EOSIO Swift includes a default RPC Provider implementation ([`EosioRpcProvider`](http://docs.eosnetwork.com/reference/swiftdocs/Sources/EosioSwift/EosioRpcProvider/EosioRpcProvider.swift)) for communicating with EOSIO nodes using the [EOSIO RPC API](https://developers.eos.io/manuals/eos/latest/nodeos/plugins/chain_api_plugin/api-reference/index). Alternate RPC providers can be used assuming they conform to the minimal [`EosioRpcProviderProtocol`](http://docs.eosnetwork.com/reference/swiftdocs/Sources/EosioSwift/EosioRpcProviderProtocol/EosioRpcProviderProtocol.swift). The core EOSIO SDK for Swift library depends only on five of the six RPC endpoints set forth in that Protocol. `pushTransaction` is no longer used by the core library but has been retained for backwards compatibility. Other endpoints, however, are exposed in the default [`EosioRpcProvider`](http://docs.eosnetwork.com/reference/swiftdocs/Sources/EosioSwift/EosioRpcProvider/EosioRpcProvider.swift).
[![Software License](https://img.shields.io/badge/license-MIT-lightgrey.svg)](https://github.com/EOSIO/eosio-swift/blob/master/LICENSE)
   * ABIEOS Serialization Provider, a pluggable serialization provider for EosioSwift. Serialization providers are responsible for ABI-driven transaction and action serialization and deserialization between JSON and binary data representations. This particular serialization provider wraps [ABIEOS](https://github.com/EOSIO/abieos), a C/C++ library that facilitates this conversion.
   * If you wish to use all of the components, add the `EosioSwift`, `EosioSwiftAbieosSerializationProvider`, `EosioSwiftEcc` and `EosioSwiftSoftkeySignatureProvider` products from `https://github.com/EOSIO/eosio-swift` to your application dependencies.
        .package(name: "EosioSwift", url: "https://github.com/EOSIO/eosio-swift", from: "1.0.0"))
   * Important: Softkey Signature Provider stores keys in memory and is therefore not secure. It should only be used for development purposes. In production, we strongly recommend using a signature provider that interfaces with a secure vault, authenticator or wallet, such as the Vault Signature Provider from [EOSIO SDK for Swift: Vault](https://github.com/EOSIO/eosio-swift-vault).
Generally, signature providers are called by [`EosioTransaction`](http://docs.eosnetwork.com/reference/swiftdocs/Sources/http://docs.eosnetwork.com/reference/swiftdocs/Sources/EosioSwift/EosioTransaction/EosioTransaction.swift) during signing. ([See an example here.](https://github.com/EOSIO/eosio-swift#basic-usage)) If you find, however, that you need to get available keys or request signing directly, this library can be invoked as follows:
  * Utilities for key generation and management and other signing functionality can be found in the [EOSIO SDK for Swift: Vault](https://github.com/EOSIO/eosio-swift-vault) library.
If you'd like to see EOSIO SDK for Swift in action, check out our open source [iOS Example App](https://github.com/EOSIO/eosio-swift-ios-example-app)--a working application that fetches an account's token balance and pushes a transfer action.
  * The Signature Provider abstraction is arguably the most useful of all of the [EOSIO SDK for Swift](https://github.com/EOSIO/eosio-swift) providers. It is responsible for:
By simply switching out the signature provider on a transaction, signature requests can be routed any number of ways. Need software signing? [Configure the `EosioTransaction`](#basic-usage) with the [Softkey Signature Provider](#softkey-signature-provider-usage) signature provider. Need a signature from keys in the platform's Keychain or Secure Enclave? 
  * Take a look at the [Vault Signature Provider](https://github.com/EOSIO/eosio-swift-vault). Need signatures from a wallet on the user's device? A signature provider can do that too!
While it is possible to use `EosioSoftkeySignatureProvider`, [Vault Signature Provider](https://github.com/EOSIOeosio-swift-vault), a signature provider implementation for signing transactions using keys stored in Keychain or the device's Secure Enclave, is strongly recommended.
  * Interested in contributing? That's awesome! Here are some [Contribution Guidelines](https://github.com/EOSIO/eosio-swift/blob/master/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/EOSIO/eosio-swift/blob/master/CONTRIBUTING.md#conduct).
  * We're always looking for ways to improve EOSIO SDK for Swift. Check out our [#enhancement Issues](https://github.com/EOSIO/eosio-swift/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement) for ways you can pitch in.
[MIT](https://github.com/EOSIO/eosio-swift/blob/master/LICENSE)

- [ ] mandel/docs/02_cleos/02_how-to-guides/how-to-get-block-information.md
  * cleos -u https://api.testnet.eos.io get block 48351112
  * cleos -u https://api.testnet.eos.io get block 
  *  02e1c7888a92206573ae38d00e09366c7ba7bc54cd8b7996506f7d2a619c43ba

- [ ] welcome/docs/04_protocol/index.md
  * [eosio.bios](https://developers.eos.io/manuals/eosio.contracts/latest/action-reference/eosio.bios)
  * [eosio.system](https://developers.eos.io/manuals/eosio.contracts/latest/action-reference/eosio.system)
  * [eosio.msig](https://developers.eos.io/manuals/eosio.contracts/latest/action-reference/eosio.msig)
  * [eosio.token](https://developers.eos.io/manuals/eosio.contracts/latest/action-reference/eosio.token)
  * [eosio.wrap](https://developers.eos.io/manuals/eosio.contracts/latest/action-reference/eosio.wrap)
  * [System accounts](https://developers.eos.io/manuals/eosio.contracts/latest/index/#system-contracts-system-accounts-priviledged-accounts)
  * [RAM](https://developers.eos.io/manuals/eosio.contracts/latest/index/#ram)
  * [CPU](https://developers.eos.io/manuals/eosio.contracts/latest/index/#cpu)
  * [NET](https://developers.eos.io/manuals/eosio.contracts/latest/index/#net)
  * [Stake](https://developers.eos.io/manuals/eosio.contracts/latest/index/#stake)
  * [Vote](https://developers.eos.io/manuals/eosio.contracts/latest/index/#vote)

- [ ] mandel-contracts/docs/04_guides/05_how-to-create-issue-and-transfer-a-token.md
  * Now check if "bob" got the tokens using [cleos get currency balance](https://developers.eos.io/manuals/eos/latest/cleos/command-reference/get/currency-balance)
git clone https://github.com/EOSIO/eosio.contracts --branch master --single-branch

- [ ] mandel-contracts/docs/04_guides/08_configure-use-powerup-resource-model.md
  * `1.` Build [eosio.contracts](https://github.com/EOSIO/eosio.contracts) with `powerup` code. Version **1.9.x** or greater .

**Comment by ericpassmore** [comment]
completed
